import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "LuminoLens",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link href='https://fonts.googleapis.com/css?family=Instrument Sans' rel='stylesheet'></link>
      </head>
      <body>
        {children}
      </body>
    </html>
  );
}
